package core

import (
	"time"

	"github.com/google/uuid"
)

// Alert represents a security alert generated by rule matches
type Alert struct {
	AlertID      string      `json:"alert_id" bson:"alert_id" example:"alert-123"`
	RuleID       string      `json:"rule_id" bson:"rule_id" example:"failed_login"`
	EventID      string      `json:"event_id" bson:"event_id" example:"event-456"`
	Timestamp    time.Time   `json:"timestamp" bson:"timestamp" swaggertype:"string" example:"2023-10-31T12:00:00Z"`
	Severity     string      `json:"severity" bson:"severity" example:"Warning"`
	Status       AlertStatus `json:"status" bson:"status" example:"Pending"` // Pending, Acknowledged, Dismissed
	JiraTicketID string      `json:"jira_ticket_id,omitempty" bson:"jira_ticket_id,omitempty" example:"PROJ-123"`
	Event        *Event      `json:"event" bson:"event"`
}

// NewAlert creates a new Alert with a generated UUID
func NewAlert(ruleID, eventID string, severity string, event *Event) *Alert {
	return &Alert{
		AlertID:   uuid.New().String(),
		RuleID:    ruleID,
		EventID:   eventID,
		Timestamp: time.Now().UTC(),
		Severity:  severity,
		Status:    AlertStatusPending,
		Event:     event,
	}
}
