// Code generated by MockGen. DO NOT EDIT.
// Source: rulestorage.go

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mongo "go.mongodb.org/mongo-driver/mongo"
	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MockRuleCursor is a mock of RuleCursor interface.
type MockRuleCursor struct {
	ctrl     *gomock.Controller
	recorder *MockRuleCursorMockRecorder
}

// MockRuleCursorMockRecorder is the mock recorder for MockRuleCursor.
type MockRuleCursorMockRecorder struct {
	mock *MockRuleCursor
}

// NewMockRuleCursor creates a new mock instance.
func NewMockRuleCursor(ctrl *gomock.Controller) *MockRuleCursor {
	mock := &MockRuleCursor{ctrl: ctrl}
	mock.recorder = &MockRuleCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleCursor) EXPECT() *MockRuleCursorMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockRuleCursor) All(ctx context.Context, results interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, results)
	ret0, _ := ret[0].(error)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockRuleCursorMockRecorder) All(ctx, results interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockRuleCursor)(nil).All), ctx, results)
}

// Close mocks base method.
func (m *MockRuleCursor) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRuleCursorMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRuleCursor)(nil).Close), ctx)
}

// Err mocks base method.
func (m *MockRuleCursor) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockRuleCursorMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockRuleCursor)(nil).Err))
}

// MockRuleSingleResult is a mock of RuleSingleResult interface.
type MockRuleSingleResult struct {
	ctrl     *gomock.Controller
	recorder *MockRuleSingleResultMockRecorder
}

// MockRuleSingleResultMockRecorder is the mock recorder for MockRuleSingleResult.
type MockRuleSingleResultMockRecorder struct {
	mock *MockRuleSingleResult
}

// NewMockRuleSingleResult creates a new mock instance.
func NewMockRuleSingleResult(ctrl *gomock.Controller) *MockRuleSingleResult {
	mock := &MockRuleSingleResult{ctrl: ctrl}
	mock.recorder = &MockRuleSingleResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleSingleResult) EXPECT() *MockRuleSingleResultMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockRuleSingleResult) Decode(v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockRuleSingleResultMockRecorder) Decode(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockRuleSingleResult)(nil).Decode), v)
}

// MockRuleCollection is a mock of RuleCollection interface.
type MockRuleCollection struct {
	ctrl     *gomock.Controller
	recorder *MockRuleCollectionMockRecorder
}

// MockRuleCollectionMockRecorder is the mock recorder for MockRuleCollection.
type MockRuleCollectionMockRecorder struct {
	mock *MockRuleCollection
}

// NewMockRuleCollection creates a new mock instance.
func NewMockRuleCollection(ctrl *gomock.Controller) *MockRuleCollection {
	mock := &MockRuleCollection{ctrl: ctrl}
	mock.recorder = &MockRuleCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleCollection) EXPECT() *MockRuleCollectionMockRecorder {
	return m.recorder
}

// DeleteOne mocks base method.
func (m *MockRuleCollection) DeleteOne(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions) (*mongo.DeleteResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOne", varargs...)
	ret0, _ := ret[0].(*mongo.DeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockRuleCollectionMockRecorder) DeleteOne(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockRuleCollection)(nil).DeleteOne), varargs...)
}

// Find mocks base method.
func (m *MockRuleCollection) Find(ctx context.Context, filter interface{}, opts ...*options.FindOptions) (RuleCursor, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(RuleCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRuleCollectionMockRecorder) Find(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRuleCollection)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockRuleCollection) FindOne(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) RuleSingleResult {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(RuleSingleResult)
	return ret0
}

// FindOne indicates an expected call of FindOne.
func (mr *MockRuleCollectionMockRecorder) FindOne(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockRuleCollection)(nil).FindOne), varargs...)
}

// InsertOne mocks base method.
func (m *MockRuleCollection) InsertOne(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, document}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOne", varargs...)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockRuleCollectionMockRecorder) InsertOne(ctx, document interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, document}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockRuleCollection)(nil).InsertOne), varargs...)
}

// UpdateOne mocks base method.
func (m *MockRuleCollection) UpdateOne(ctx context.Context, filter, update interface{}, opts ...*options.UpdateOptions) (*mongo.UpdateResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter, update}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOne", varargs...)
	ret0, _ := ret[0].(*mongo.UpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockRuleCollectionMockRecorder) UpdateOne(ctx, filter, update interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter, update}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockRuleCollection)(nil).UpdateOne), varargs...)
}
