// Code generated by MockGen. DO NOT EDIT.
// Source: actionstorage.go

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mongo "go.mongodb.org/mongo-driver/mongo"
	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MockActionCursor is a mock of ActionCursor interface.
type MockActionCursor struct {
	ctrl     *gomock.Controller
	recorder *MockActionCursorMockRecorder
}

// MockActionCursorMockRecorder is the mock recorder for MockActionCursor.
type MockActionCursorMockRecorder struct {
	mock *MockActionCursor
}

// NewMockActionCursor creates a new mock instance.
func NewMockActionCursor(ctrl *gomock.Controller) *MockActionCursor {
	mock := &MockActionCursor{ctrl: ctrl}
	mock.recorder = &MockActionCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionCursor) EXPECT() *MockActionCursorMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockActionCursor) All(ctx context.Context, results interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, results)
	ret0, _ := ret[0].(error)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockActionCursorMockRecorder) All(ctx, results interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockActionCursor)(nil).All), ctx, results)
}

// Close mocks base method.
func (m *MockActionCursor) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockActionCursorMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockActionCursor)(nil).Close), ctx)
}

// Decode mocks base method.
func (m *MockActionCursor) Decode(v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockActionCursorMockRecorder) Decode(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockActionCursor)(nil).Decode), v)
}

// Err mocks base method.
func (m *MockActionCursor) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockActionCursorMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockActionCursor)(nil).Err))
}

// Next mocks base method.
func (m *MockActionCursor) Next(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockActionCursorMockRecorder) Next(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockActionCursor)(nil).Next), ctx)
}

// MockActionSingleResult is a mock of ActionSingleResult interface.
type MockActionSingleResult struct {
	ctrl     *gomock.Controller
	recorder *MockActionSingleResultMockRecorder
}

// MockActionSingleResultMockRecorder is the mock recorder for MockActionSingleResult.
type MockActionSingleResultMockRecorder struct {
	mock *MockActionSingleResult
}

// NewMockActionSingleResult creates a new mock instance.
func NewMockActionSingleResult(ctrl *gomock.Controller) *MockActionSingleResult {
	mock := &MockActionSingleResult{ctrl: ctrl}
	mock.recorder = &MockActionSingleResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionSingleResult) EXPECT() *MockActionSingleResultMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockActionSingleResult) Decode(v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockActionSingleResultMockRecorder) Decode(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockActionSingleResult)(nil).Decode), v)
}

// MockActionCollection is a mock of ActionCollection interface.
type MockActionCollection struct {
	ctrl     *gomock.Controller
	recorder *MockActionCollectionMockRecorder
}

// MockActionCollectionMockRecorder is the mock recorder for MockActionCollection.
type MockActionCollectionMockRecorder struct {
	mock *MockActionCollection
}

// NewMockActionCollection creates a new mock instance.
func NewMockActionCollection(ctrl *gomock.Controller) *MockActionCollection {
	mock := &MockActionCollection{ctrl: ctrl}
	mock.recorder = &MockActionCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionCollection) EXPECT() *MockActionCollectionMockRecorder {
	return m.recorder
}

// DeleteOne mocks base method.
func (m *MockActionCollection) DeleteOne(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions) (*mongo.DeleteResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOne", varargs...)
	ret0, _ := ret[0].(*mongo.DeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockActionCollectionMockRecorder) DeleteOne(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockActionCollection)(nil).DeleteOne), varargs...)
}

// Find mocks base method.
func (m *MockActionCollection) Find(ctx context.Context, filter interface{}, opts ...*options.FindOptions) (ActionCursor, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(ActionCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockActionCollectionMockRecorder) Find(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockActionCollection)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockActionCollection) FindOne(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) ActionSingleResult {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(ActionSingleResult)
	return ret0
}

// FindOne indicates an expected call of FindOne.
func (mr *MockActionCollectionMockRecorder) FindOne(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockActionCollection)(nil).FindOne), varargs...)
}

// Indexes mocks base method.
func (m *MockActionCollection) Indexes() mongo.IndexView {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Indexes")
	ret0, _ := ret[0].(mongo.IndexView)
	return ret0
}

// Indexes indicates an expected call of Indexes.
func (mr *MockActionCollectionMockRecorder) Indexes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indexes", reflect.TypeOf((*MockActionCollection)(nil).Indexes))
}

// InsertOne mocks base method.
func (m *MockActionCollection) InsertOne(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, document}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOne", varargs...)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockActionCollectionMockRecorder) InsertOne(ctx, document interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, document}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockActionCollection)(nil).InsertOne), varargs...)
}

// UpdateOne mocks base method.
func (m *MockActionCollection) UpdateOne(ctx context.Context, filter, update interface{}, opts ...*options.UpdateOptions) (*mongo.UpdateResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter, update}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOne", varargs...)
	ret0, _ := ret[0].(*mongo.UpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockActionCollectionMockRecorder) UpdateOne(ctx, filter, update interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter, update}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockActionCollection)(nil).UpdateOne), varargs...)
}
