// Code generated by MockGen. DO NOT EDIT.
// Source: correlationrulestorage.go

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mongo "go.mongodb.org/mongo-driver/mongo"
	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MockCorrelationRuleCursor is a mock of CorrelationRuleCursor interface.
type MockCorrelationRuleCursor struct {
	ctrl     *gomock.Controller
	recorder *MockCorrelationRuleCursorMockRecorder
}

// MockCorrelationRuleCursorMockRecorder is the mock recorder for MockCorrelationRuleCursor.
type MockCorrelationRuleCursorMockRecorder struct {
	mock *MockCorrelationRuleCursor
}

// NewMockCorrelationRuleCursor creates a new mock instance.
func NewMockCorrelationRuleCursor(ctrl *gomock.Controller) *MockCorrelationRuleCursor {
	mock := &MockCorrelationRuleCursor{ctrl: ctrl}
	mock.recorder = &MockCorrelationRuleCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCorrelationRuleCursor) EXPECT() *MockCorrelationRuleCursorMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockCorrelationRuleCursor) All(ctx context.Context, results interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, results)
	ret0, _ := ret[0].(error)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockCorrelationRuleCursorMockRecorder) All(ctx, results interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockCorrelationRuleCursor)(nil).All), ctx, results)
}

// Close mocks base method.
func (m *MockCorrelationRuleCursor) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCorrelationRuleCursorMockRecorder) Close(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCorrelationRuleCursor)(nil).Close), ctx)
}

// Decode mocks base method.
func (m *MockCorrelationRuleCursor) Decode(v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockCorrelationRuleCursorMockRecorder) Decode(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockCorrelationRuleCursor)(nil).Decode), v)
}

// Err mocks base method.
func (m *MockCorrelationRuleCursor) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockCorrelationRuleCursorMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockCorrelationRuleCursor)(nil).Err))
}

// Next mocks base method.
func (m *MockCorrelationRuleCursor) Next(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockCorrelationRuleCursorMockRecorder) Next(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockCorrelationRuleCursor)(nil).Next), ctx)
}

// MockCorrelationRuleSingleResult is a mock of CorrelationRuleSingleResult interface.
type MockCorrelationRuleSingleResult struct {
	ctrl     *gomock.Controller
	recorder *MockCorrelationRuleSingleResultMockRecorder
}

// MockCorrelationRuleSingleResultMockRecorder is the mock recorder for MockCorrelationRuleSingleResult.
type MockCorrelationRuleSingleResultMockRecorder struct {
	mock *MockCorrelationRuleSingleResult
}

// NewMockCorrelationRuleSingleResult creates a new mock instance.
func NewMockCorrelationRuleSingleResult(ctrl *gomock.Controller) *MockCorrelationRuleSingleResult {
	mock := &MockCorrelationRuleSingleResult{ctrl: ctrl}
	mock.recorder = &MockCorrelationRuleSingleResultMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCorrelationRuleSingleResult) EXPECT() *MockCorrelationRuleSingleResultMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockCorrelationRuleSingleResult) Decode(v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockCorrelationRuleSingleResultMockRecorder) Decode(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockCorrelationRuleSingleResult)(nil).Decode), v)
}

// MockCorrelationRuleCollection is a mock of CorrelationRuleCollection interface.
type MockCorrelationRuleCollection struct {
	ctrl     *gomock.Controller
	recorder *MockCorrelationRuleCollectionMockRecorder
}

// MockCorrelationRuleCollectionMockRecorder is the mock recorder for MockCorrelationRuleCollection.
type MockCorrelationRuleCollectionMockRecorder struct {
	mock *MockCorrelationRuleCollection
}

// NewMockCorrelationRuleCollection creates a new mock instance.
func NewMockCorrelationRuleCollection(ctrl *gomock.Controller) *MockCorrelationRuleCollection {
	mock := &MockCorrelationRuleCollection{ctrl: ctrl}
	mock.recorder = &MockCorrelationRuleCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCorrelationRuleCollection) EXPECT() *MockCorrelationRuleCollectionMockRecorder {
	return m.recorder
}

// DeleteOne mocks base method.
func (m *MockCorrelationRuleCollection) DeleteOne(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions) (*mongo.DeleteResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOne", varargs...)
	ret0, _ := ret[0].(*mongo.DeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOne indicates an expected call of DeleteOne.
func (mr *MockCorrelationRuleCollectionMockRecorder) DeleteOne(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*MockCorrelationRuleCollection)(nil).DeleteOne), varargs...)
}

// Find mocks base method.
func (m *MockCorrelationRuleCollection) Find(ctx context.Context, filter interface{}, opts ...*options.FindOptions) (CorrelationRuleCursor, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Find", varargs...)
	ret0, _ := ret[0].(CorrelationRuleCursor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCorrelationRuleCollectionMockRecorder) Find(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCorrelationRuleCollection)(nil).Find), varargs...)
}

// FindOne mocks base method.
func (m *MockCorrelationRuleCollection) FindOne(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) CorrelationRuleSingleResult {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindOne", varargs...)
	ret0, _ := ret[0].(CorrelationRuleSingleResult)
	return ret0
}

// FindOne indicates an expected call of FindOne.
func (mr *MockCorrelationRuleCollectionMockRecorder) FindOne(ctx, filter interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockCorrelationRuleCollection)(nil).FindOne), varargs...)
}

// InsertOne mocks base method.
func (m *MockCorrelationRuleCollection) InsertOne(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, document}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InsertOne", varargs...)
	ret0, _ := ret[0].(*mongo.InsertOneResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockCorrelationRuleCollectionMockRecorder) InsertOne(ctx, document interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, document}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockCorrelationRuleCollection)(nil).InsertOne), varargs...)
}

// UpdateOne mocks base method.
func (m *MockCorrelationRuleCollection) UpdateOne(ctx context.Context, filter, update interface{}, opts ...*options.UpdateOptions) (*mongo.UpdateResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, filter, update}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOne", varargs...)
	ret0, _ := ret[0].(*mongo.UpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOne indicates an expected call of UpdateOne.
func (mr *MockCorrelationRuleCollectionMockRecorder) UpdateOne(ctx, filter, update interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, filter, update}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*MockCorrelationRuleCollection)(nil).UpdateOne), varargs...)
}
