// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/actions": {
            "get": {
                "description": "Returns a list of all actions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Get actions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.Action"
                            }
                        }
                    },
                    "503": {
                        "description": "Action storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new action",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Create action",
                "parameters": [
                    {
                        "description": "Action object",
                        "name": "action",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.Action"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/core.Action"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Action storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/actions/{id}": {
            "get": {
                "description": "Get an action by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Get action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Action ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.Action"
                        }
                    },
                    "404": {
                        "description": "Action not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Action storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing action",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Update action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Action ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Action object",
                        "name": "action",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.Action"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.Action"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Action not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Action storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an action by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Delete action",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Action ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Action deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Action not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Action storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alerts": {
            "get": {
                "description": "Returns a list of alerts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Get alerts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.Alert"
                            }
                        }
                    }
                }
            }
        },
        "/api/alerts/{id}/acknowledge": {
            "post": {
                "description": "Acknowledge an alert by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Acknowledge alert",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Alert ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert acknowledged",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Alert not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Alert storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/alerts/{id}/dismiss": {
            "post": {
                "description": "Dismiss an alert by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Dismiss alert",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Alert ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Alert not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Alert storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/correlation-rules": {
            "get": {
                "description": "Returns a list of all correlation rules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation-rules"
                ],
                "summary": "Get correlation rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.CorrelationRule"
                            }
                        }
                    },
                    "503": {
                        "description": "Correlation rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new correlation rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation-rules"
                ],
                "summary": "Create correlation rule",
                "parameters": [
                    {
                        "description": "Correlation Rule object",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.CorrelationRule"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/core.CorrelationRule"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Correlation rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/correlation-rules/{id}": {
            "get": {
                "description": "Get a correlation rule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation-rules"
                ],
                "summary": "Get correlation rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Correlation Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.CorrelationRule"
                        }
                    },
                    "404": {
                        "description": "Correlation rule not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Correlation rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing correlation rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation-rules"
                ],
                "summary": "Update correlation rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Correlation Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Correlation Rule object",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.CorrelationRule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.CorrelationRule"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Correlation rule not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Correlation rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a correlation rule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "correlation-rules"
                ],
                "summary": "Delete correlation rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Correlation Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Correlation rule deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Correlation rule not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Correlation rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/dashboard": {
            "get": {
                "description": "Returns dashboard statistics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get dashboard stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/dashboard/chart": {
            "get": {
                "description": "Returns historical chart data for events and alerts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get dashboard chart data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "503": {
                        "description": "Storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/events": {
            "get": {
                "description": "Returns a list of recent security events",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get events",
                "parameters": [
                    {
                        "maximum": 1000,
                        "minimum": 1,
                        "type": "integer",
                        "default": 100,
                        "description": "Maximum number of results (1-1000)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cerberus_core.Event"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/listeners": {
            "get": {
                "description": "Returns information about active listeners",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get listeners",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/rules": {
            "get": {
                "description": "Returns a list of all detection rules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Get rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/core.Rule"
                            }
                        }
                    },
                    "503": {
                        "description": "Rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new detection rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Create rule",
                "parameters": [
                    {
                        "description": "Rule object",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.Rule"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/core.Rule"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/rules/{id}": {
            "put": {
                "description": "Update an existing detection rule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Update rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rule object",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.Rule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.Rule"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Rule not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a detection rule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Delete rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Rule deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Rule not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Rule storage not available",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/rules/{id}": {
            "get": {
                "description": "Get a detection rule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rules"
                ],
                "summary": "Get rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/core.Rule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cerberus_core.Event": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string",
                    "example": "event-123"
                },
                "event_type": {
                    "type": "string",
                    "example": "user_login"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": true
                },
                "raw_data": {
                    "type": "string",
                    "example": "raw log data"
                },
                "severity": {
                    "type": "string",
                    "example": "info"
                },
                "source_format": {
                    "type": "string",
                    "example": "json"
                },
                "source_ip": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-10-31T12:00:00Z"
                }
            }
        },
        "core.Action": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object"
                },
                "id": {
                    "type": "string",
                    "example": "action-123"
                },
                "type": {
                    "description": "webhook, jira, etc.",
                    "type": "string",
                    "example": "webhook"
                }
            }
        },
        "core.Alert": {
            "type": "object",
            "properties": {
                "alert_id": {
                    "type": "string",
                    "example": "alert-123"
                },
                "event": {
                    "$ref": "#/definitions/cerberus_core.Event"
                },
                "event_id": {
                    "type": "string",
                    "example": "event-456"
                },
                "jira_ticket_id": {
                    "type": "string",
                    "example": "PROJ-123"
                },
                "rule_id": {
                    "type": "string",
                    "example": "failed_login"
                },
                "severity": {
                    "type": "string",
                    "example": "Warning"
                },
                "status": {
                    "description": "Pending, Acknowledged, Dismissed",
                    "allOf": [
                        {
                            "$ref": "#/definitions/core.AlertStatus"
                        }
                    ],
                    "example": "Pending"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2023-10-31T12:00:00Z"
                }
            }
        },
        "core.AlertStatus": {
            "type": "string",
            "enum": [
                "Pending",
                "Acknowledged",
                "Dismissed"
            ],
            "x-enum-varnames": [
                "AlertStatusPending",
                "AlertStatusAcknowledged",
                "AlertStatusDismissed"
            ]
        },
        "core.Condition": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string",
                    "example": "fields.status"
                },
                "logic": {
                    "description": "AND, OR (for combining conditions)",
                    "type": "string",
                    "example": "AND"
                },
                "operator": {
                    "description": "equals, not_equals, contains, starts_with, ends_with, regex, greater_than, less_than, greater_than_or_equal, less_than_or_equal",
                    "type": "string",
                    "example": "equals"
                },
                "value": {
                    "type": "string",
                    "example": "failure"
                }
            }
        },
        "core.CorrelationRule": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core.Action"
                    }
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core.Condition"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "Detects multiple failed logins"
                },
                "id": {
                    "type": "string",
                    "example": "correlation_rule_1"
                },
                "name": {
                    "type": "string",
                    "example": "Brute Force Detection"
                },
                "sequence": {
                    "description": "sequence of event types",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "user_login",
                        "user_login",
                        "user_login"
                    ]
                },
                "severity": {
                    "type": "string",
                    "example": "High"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                },
                "window": {
                    "description": "time window for correlation in nanoseconds",
                    "type": "integer",
                    "example": 300000000000
                }
            }
        },
        "core.Rule": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core.Action"
                    }
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core.Condition"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "Detects multiple failed login attempts"
                },
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "string",
                    "example": "failed_login"
                },
                "name": {
                    "type": "string",
                    "example": "Failed User Login"
                },
                "severity": {
                    "type": "string",
                    "example": "Warning"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Enter your API key",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Cerberus SIEM API",
	Description:      "API for managing Cerberus SIEM events, alerts, rules, and configuration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
